default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: bondooman
  password:

development:
  <<: *default
  database: bondooman_development

test:
  <<: *default
  database: bondooman_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
