defaults: &defaults
  ubermensch:
    app_url: <%= ENV["UBERMENSCH_APP_URL"] %>
    app_key: <%= ENV["UBERMENSCH_APP_KEY"] %>
    app_secret: <%= ENV["UBERMENSCH_APP_SECRET"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
