default: &default
  :concurrency: 5
  :queues:
    - googleplay
    - appstore
    - mailers
    - default
  :limits:
    googleplay: 1
    appstore: 1
    mailers: 2
    default: 3

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
